services:
  - type: web
    name: ute-social-network
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne UTESocialNetwork.asgi:application -b 0.0.0.0 -p $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: ute_social_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ute-social-redis
          type: redis
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: ute_social_db
    databaseName: ute_social_db
    plan: free

redis:
  - name: ute-social-redis
    plan: free
    maxmemoryPolicy: noeviction 