# Generated by Django 5.1.6 on 2025-05-13 17:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mat_khau_hash', models.CharField(max_length=255)),
                ('anh_dai_dien', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'NGUOIDUNG',
            },
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('hinh_anh', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media')),
                ('trang_thai', models.CharField(choices=[('public', 'Công khai'), ('friend', 'Bạn bè'), ('private', 'Riêng tư')], default='public', max_length=10)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ten_nhom', models.CharField(blank=True, max_length=255, null=True)),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung')),
            ],
            options={
                'db_table': 'BAIVIET',
            },
        ),
    ]
