# Generated by Django 5.1.6 on 2025-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_photo',
            field=models.ImageField(default='default-cover.jpg', upload_to='group_cover_photos'),
        ),
    ]
