# Generated by Django 5.1.6 on 2025-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='images/resources/timeline-1.jpg', upload_to='profile_covers'),
        ),
    ]
