# Generated by Django 5.2 on 2025-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_badge_quiz_alter_profile_user_question_quizattempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d',
            new_name='option4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(),
        ),
    ]
