# Generated by Django 4.2.7 on 2025-06-19 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(help_text='Option A', max_length=255)),
                ('option_b', models.CharField(help_text='Option B', max_length=255)),
                ('option_c', models.CharField(help_text='Option C', max_length=255)),
                ('option_d', models.CharField(help_text='Option D', max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The correct answer (A, B, C, or D)', max_length=1)),
                ('created_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the question was created')),
            ],
            options={
                'verbose_name': 'English Question',
                'verbose_name_plural': 'English Questions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The answer selected by the user', max_length=1)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('answer_time', models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted')),
                ('completion_time', models.IntegerField(default=0, help_text='Time taken to complete in seconds')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.englishquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answer_time'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
