# Generated by Django 4.2.7 on 2025-06-17 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(help_text='Option A', max_length=255)),
                ('option_b', models.CharField(help_text='Option B', max_length=255)),
                ('option_c', models.CharField(help_text='Option C', max_length=255)),
                ('option_d', models.CharField(help_text='Option D', max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The correct answer (A, B, C, or D)', max_length=1)),
                ('created_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the question was created')),
            ],
            options={
                'verbose_name': 'English Question',
                'verbose_name_plural': 'English Questions',
                'ordering': ['-created_date'],
            },
        ),
    ]
